[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "my_calculator"
version = "1.0.0"
description = "Modul kalkulator sederhana untuk example repositori"
readme = "README.md"
requires-python = ">=3.8"
authors = [
    { name = "Alfin", email = "halovinaofficial@gmail.com" }
]

[tool.setuptools.packages.find]
where = ["src"]
